name: Node App CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: harbor.local
  PROJECT: node-devops
  IMAGE_NAME: node-app
  NAMESPACE: node-app

jobs:

  build-and-deploy:

    runs-on: [self-hosted]

    steps:

    - name: checkout repository
      users: actions/checkout@v4


    # -------TEST STAGE-------------

    - name: Setup Node
      users: actions/setup-node@v4
      with: 
      node-version: 20

    - name Install Dependencies
      run: npm test

    #-------BUILD IMAGE---------------

    - name: Build Docker Image
      run: |
        docker build -t $REGISTRY/$PROJECT/$IMAGE_NAME:${{ github.sha }} .

    #--------------- LOGIN TO HARBOR---------------
    - name: login to harbor
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | docker login $REGISTRY \
        -u ${{ secrets.HARBOR_USER }} --password-stdin

    #-----------------PUSH IMAGE--------------------
    - name: push Docker Image
      run: |
        docker push $REGISTRY/$PROJECT/$IMAGE_NAME:${{ github.sha }}


    #----------------DEPLOY TO k8s -------------------------
    - name: update kubernetes Deployment
      run: |
        kubectl set image deployment/node-app \
        node-app=$REGISTRY/$PROJECT/$IMAGE_NAME:${{ github.sha }} \
        -n $NAMESPACE
