name: Node App CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: harbor.local
  PROJECT: node-devops
  IMAGE_NAME: node-app
  NAMESPACE: node-app
  CONTROL_PLANE: 192.168.29.111

jobs:

  build-and-deploy:

    runs-on: [self-hosted, Linux, X64]

    steps:

    # -----------------------------
    # Checkout Code
    # -----------------------------
    - name: Checkout Repository
      uses: actions/checkout@v4

    # -----------------------------
    # Setup Node
    # -----------------------------
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # -----------------------------
    # Install Dependencies
    # -----------------------------
    - name: Install Dependencies
      run: npm install

    # -----------------------------
    # Run Tests
    # -----------------------------
    - name: Run Tests
      run: npm test

    # -----------------------------
    # Set Image Tag
    # -----------------------------
    - name: Set Image Tag
      run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

    # -----------------------------
    # Build Docker Image
    # -----------------------------
    - name: Build Docker Image
      run: |
        docker build -t $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG .
        docker tag -t $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG $REGISTRY/$PROJECT/$IMAGE_NAME:latest

    # -----------------------------
    # Harbor Login
    # -----------------------------
    - name: Login to Harbor
      env:
        HARBOR_USER: ${{ secrets.HARBOR_USER }}
        HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      run: |
        echo "$HARBOR_PASSWORD" | docker login $REGISTRY \
        --username "$HARBOR_USER" \
        --password-stdin

    # -----------------------------
    # Push Docker Image
    # -----------------------------
    - name: Push Docker Image
      run: |
        docker push $REGISTRY/$PROJECT/$IMAGE_NAME:$IMAGE_TAG
        docker push $REGISTRY/$PROJECT/$IMAGE_NAME:latest

    # -----------------------------
    # Setup SSH Key
    # -----------------------------
    - name: Setup SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $CONTROL_PLANE >> ~/.ssh/known_hosts

    # -----------------------------
    # Deploy to Kubernetes Control Plane
    # -----------------------------
    - name: Deploy to Kubernetes
      run: |
        ssh master@$CONTROL_PLANE << EOF

        cd /home/master/k8s-project2/node-app

        kubectl apply -f namespace.yaml
        kubectl apply -f harbor-secret.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

        kubectl rollout restart deployment node-app -n $NAMESPACE
        kubectl rollout status deployment node-app -n $NAMESPACE
        EOF

    # -----------------------------
    # Logout Harbor
    # -----------------------------
    - name: Logout Harbor
      run: docker logout $REGISTRY
